### ISSUE TITLE
Does this still work and is there an option that works for regular users who want to delete their own messages?

### ISSUE THREAD

**Issue by xanoni** [xwiki-labs/matrix-stfu#4]
Does this still work and is there an option that works for regular users who want to delete their own messages?

**Comment by vwkd** [comment]
I get the following error with the latest version of all packages, using the internal room ID for the room name of a direct chat room.

```sh
Removing all messages in [#xxxxxxxxxxxxxxxx:matrix.org] written by [@yyyyyyyyy:matrix.org]
Getting saved sync token...
Getting push rules...
Got saved sync token
Getting saved sync...
Got reply from saved sync, exists? false
Getting push rules failed ConnectionError: request failed: getaddrinfo ENOTFOUND undefined
    at ZZZZZZZ/node_modules/matrix-js-sdk/lib/http-api.js:777:15
    at Request._callback (ZZZZZZZ/node_modules/matrix-js-sdk/lib/http-api.js:718:9)
    at self.callback (ZZZZZZZ/node_modules/request/request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (ZZZZZZZ/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3) {
  _cause: Error: getaddrinfo ENOTFOUND undefined
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'undefined'
  }
}
```
